# Generated by Django 4.0.5 on 2022-06-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_tittle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
