# Generated by Django 4.0.5 on 2022-06-05 21:47

from django.db import migrations, models
import django.db.models.deletion
import home.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0004_remove_homepage_banner_tittle_homepage_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.fields.StreamField([('full_richtext', home.blocks.RichtextBlock())], blank=True, null=True, use_json_field=None),
        ),
    ]
